[extend]
useDefault = true

[allowlist]
description = "Allowlist for test/CI environment variables"
paths = [
  '''^\.env\.example$''',
]

[[allowlist.regexes]]
description = "Ignore placeholder secrets in .env.example"
regex = '''APP_SECRET=dm6710T5HURxvZag3b93c2bPMUybcRZs6P4IOk7LFkkc5DHZAxWUVlHOovcdN7GD'''
